name: Airflow DAGs deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: id_rsa
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host 85.209.9.101
              HostName 85.209.9.101
              User root
              IdentityFile ~/.ssh/id_rsa
              Port 22

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fabric==2.6.0

      - name: Run fabfile
        run: fab deploy